version: '3'
services:
  website:
    build: .              # <--- Changed from 'image: nginx'
    restart: always
    networks:
      - default
networks:
  default:
    external: true
    name: clav

